"""Добавление параметров дедлайна для classic-задач

Revision ID: 068d5de3397f
Revises: 059d760bec2c
Create Date: 2026-04-22 16:19:41.844663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068d5de3397f'
down_revision: Union[str, Sequence[str], None] = '059d760bec2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('executor_deadline_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('current_executor_deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'current_executor_deadline')
    op.drop_column('tasks', 'executor_deadline_minutes')
    # ### end Alembic commands ###
