"""Добавили сообщения для проекта

Revision ID: 1b52e1d30eaf
Revises: 2bdcc7f85e32
Create Date: 2026-04-22 20:21:09.855609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b52e1d30eaf'
down_revision: Union[str, Sequence[str], None] = '2bdcc7f85e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_messages_project_id_created_at', 'project_messages', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_messages_task_id_created_at', 'messages', ['task_id', 'created_at'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index('idx_messages_task_id_created_at', table_name='messages')
    op.drop_index('idx_project_messages_project_id_created_at', table_name='project_messages')
    op.drop_table('project_messages')
    # ### end Alembic commands ###
