"""Добавление ролей для idea_response и сделали full_description nullable

Revision ID: 1db292f3de45
Revises: 068d5de3397f
Create Date: 2026-04-22 18:39:16.167841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db292f3de45'
down_revision: Union[str, Sequence[str], None] = '068d5de3397f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Добавляем колонку как nullable
    op.add_column('idea_responses', sa.Column('role', sa.String(length=50), nullable=True))
    
    # 2. Заполняем существующие записи значением по умолчанию
    op.execute("UPDATE idea_responses SET role = 'unknown' WHERE role IS NULL")
    
    # 3. Делаем колонку NOT NULL
    op.alter_column('idea_responses', 'role', nullable=False)
    
    # 4. Изменяем full_description в ideas
    op.alter_column('ideas', 'full_description',
               existing_type=sa.Text(),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ideas', 'full_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('idea_responses', 'role')
    # ### end Alembic commands ###
