"""Добавили username и avatar_url

Revision ID: 236db7e4fb92
Revises: 6feb3f01bb65
Create Date: 2026-04-22 19:24:50.020646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236db7e4fb92'
down_revision: Union[str, Sequence[str], None] = '6feb3f01bb65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialist_profiles', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('specialist_profiles', 'avatar_url')
    # ### end Alembic commands ###
