"""Добавили индексы для производительности

Revision ID: 2bdcc7f85e32
Revises: 236db7e4fb92
Create Date: 2026-04-22 19:27:24.378410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bdcc7f85e32'
down_revision: Union[str, Sequence[str], None] = '236db7e4fb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_idea_responses_status'), 'idea_responses', ['status'], unique=False)
    op.create_index(op.f('ix_ideas_status'), 'ideas', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_author_id'), 'tasks', ['author_id'], unique=False)
    op.create_index(op.f('ix_tasks_execution_mode'), 'tasks', ['execution_mode'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_execution_mode'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_author_id'), table_name='tasks')
    op.drop_index(op.f('ix_ideas_status'), table_name='ideas')
    op.drop_index(op.f('ix_idea_responses_status'), table_name='idea_responses')
    # ### end Alembic commands ###
