"""Добавили парочку данных для корректной работы всей БД

Revision ID: 384430bb8c9e
Revises: 1b52e1d30eaf
Create Date: 2026-04-22 21:18:24.306170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384430bb8c9e'
down_revision: Union[str, Sequence[str], None] = '1b52e1d30eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
