"""Добавлен статус задачи в таблицу TaskExecutions

Revision ID: 8d7f328613a2
Revises: d500f6bbbb9b
Create Date: 2026-04-17 20:20:28.917326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7f328613a2'
down_revision: Union[str, Sequence[str], None] = 'd500f6bbbb9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_executions', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_executions', 'status')
    # ### end Alembic commands ###
