"""Добавление полей для выполнения задач

Revision ID: a3ba8dbd6638
Revises: aee0b4f582ca
Create Date: 2026-04-10 09:35:05.367300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ba8dbd6638'
down_revision: Union[str, Sequence[str], None] = 'aee0b4f582ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_executions', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_executions', 'comment')
    # ### end Alembic commands ###
