"""Добавление полей для выполнения задач

Revision ID: c77c939b5b06
Revises: a3ba8dbd6638
Create Date: 2026-04-10 09:58:59.724279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77c939b5b06'
down_revision: Union[str, Sequence[str], None] = 'a3ba8dbd6638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
